"use client";

import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, BookOpen, Check, CheckCircle2, ChevronRight, FileText, Home, Landmark, Layers, MapPin, MessageSquareText, Play, ShieldCheck, Trees, Video, AlertCircle, Lightbulb, LoaderCircle, ArrowLeft, Map } from "lucide-react";
import ImpactMap from "./impact-map";
import { type SourceDocument } from "./source-library";
import { ORDINANCES, MEETING, TRANSCRIPT_REPO, asset, githubUrl, officialSourcePath, rawUrl, type CivicProgress, type Ordinance } from "@/lib/civic-data";
import { sourceContentUrl } from "@/lib/source-content";

export function OrdinanceIcon({ ordinance, size = 21 }: { ordinance: Ordinance; size?: number }) {
  if (ordinance.icon === "home") return <Home size={size}/>;
  if (ordinance.icon === "map") return <Map size={size}/>;
  if (ordinance.icon === "trees") return <Trees size={size}/>;
  if (ordinance.icon === "shield") return <ShieldCheck size={size}/>;
  return <Layers size={size}/>;
}
export function officialDocument(id: string, title: string, originalUrl: string): SourceDocument {
  const local = officialSourcePath(id);
  return { title, kind: "document", url: local ? asset(local) : originalUrl, originalUrl, downloadUrl: originalUrl, external: !local };
}
export const transcriptDocument: SourceDocument = { title: "City Council transcript · January 26, 2026", kind: "text", url: sourceContentUrl(TRANSCRIPT_REPO, MEETING.transcriptPath), originalUrl: githubUrl(TRANSCRIPT_REPO, MEETING.transcriptPath), downloadUrl: rawUrl(TRANSCRIPT_REPO, MEETING.transcriptPath), repo: TRANSCRIPT_REPO, path: MEETING.transcriptPath, warning: "Auto-generated captions can contain errors, particularly names. Verify quotations against the official meeting video." };
const STAGES = [{ id: "read", label: "Read the record", icon: BookOpen }, { id: "watch", label: "Follow the session", icon: Play }, { id: "impact", label: "Explore the impact", icon: MapPin }, { id: "reflect", label: "Your perspective", icon: MessageSquareText }];
const CHECKPOINTS: Record<string, { question: string; answers: string[]; correct: number }> = {
  home: { question: "What does this accessory-dwelling proposal remove?", answers: ["The owner-occupancy requirement", "Every building permit requirement", "All residential zoning rules"], correct: 0 },
  map: { question: "What would this annexation change if enacted?", answers: ["The price of every home", "Municipal jurisdiction over the described tracts", "Approval of every future building"], correct: 1 },
  trees: { question: "What is the subject of proposed Chapter 8.72?", answers: ["All activity in public parks", "Private displays inside homes", "Unauthorized private displays on public property"], correct: 2 },
  shield: { question: "Does a third-reading agenda entry prove an ordinance was adopted?", answers: ["Yes, adoption is automatic", "No — the recorded action must be checked", "Yes, if public testimony is given"], correct: 1 },
  layers: { question: "What would AG and MR zoning classifications establish?", answers: ["Automatic permits for every development", "The price of each parcel", "Land-use classifications for the specified tracts"], correct: 2 },
};

export function ImpactSummary({ ordinance, proposed = true }: { ordinance: Ordinance; proposed?: boolean }) {
  return <div className="impact-summary"><div className="impact-evidence-label"><span className={`evidence-dot ${proposed ? "" : "muted"}`}/>{proposed ? "PROPOSED RULE CHANGE" : "EXISTING-RULE CONTEXT"}</div><h3>{proposed ? "What would change?" : "Before this proposal"}</h3><p>{proposed ? ordinance.proposed : ordinance.baseline}</p><div className="uncertainty-box"><AlertCircle size={17}/><div><strong>What the record doesn’t establish</strong><p>{ordinance.uncertainty}</p></div></div><div className="recorded-action"><CheckCircle2 size={17}/><div><strong>At the January 26 session</strong><p>{ordinance.outcome}</p></div></div></div>;
}

export default function SessionWorkspace({ selected, progress, onSelect, onOpen, onSave, onMap, onBack }: { selected: Ordinance; progress: CivicProgress[]; onSelect: (id: string) => void; onOpen: (doc: SourceDocument) => void; onSave: (ordinanceId: string, stage: string, position: string | null, reflection: string) => Promise<boolean>; onMap: (id: string) => void; onBack: () => void }) {
  const existing = progress.find((p) => p.ordinanceId === selected.id);
  const [stage, setStage] = useState(existing?.stage || "read");
  const [position, setPosition] = useState<string | null>(existing?.position || null);
  const [reflection, setReflection] = useState(existing?.reflection || "");
  const [saving, setSaving] = useState(false);
  const [proposed, setProposed] = useState(true);
  const [answer, setAnswer] = useState<number | null>(null);
  const [saved, setSaved] = useState(false);
  useEffect(() => {
    const p = progress.find((item) => item.ordinanceId === selected.id);
    setStage(p?.stage || "read"); setPosition(p?.position || null); setReflection(p?.reflection || ""); setAnswer(null); setSaved(false);
    // Restore the selected ordinance's saved state only when the selection changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selected.id]);
  async function save(nextStage: string) {
    setSaving(true);
    const ok = await onSave(selected.id, nextStage, position, reflection);
    setSaving(false);
    if (ok) { setStage(nextStage); if (nextStage === "reflect" && (position || reflection.trim())) setSaved(true); }
  }
  const stageIndex = STAGES.findIndex((s) => s.id === stage);
  const checkpoint = CHECKPOINTS[selected.icon];
  return <section className="session-page page-enter"><div className="page-intro"><div><div className="eyebrow"><Landmark size={13}/> YOUR SEAT AT CITY HALL</div><h1>Inside Council Chambers.</h1><p>A real session. The original agenda. A closer look at what’s at stake.</p></div><button className="button button-outline" onClick={onBack}><ArrowLeft size={15}/> Back to overview</button></div>
    <div className="session-location-banner"><div><Landmark size={19}/><strong>Cheyenne Municipal Building</strong><span>2101 O’Neil Avenue · Council Chambers</span></div><span className="pill pill-neutral">Archived session · {MEETING.shortDate}</span></div>
    <div className="session-workspace"><aside className="session-agenda"><div className="session-agenda-heading"><span className="eyebrow">ON THE AGENDA</span><h3>January 26, 2026</h3><p>Regular council meeting · 6:00 PM</p></div><div className="session-agenda-list">{[...ORDINANCES].sort((a,b) => a.item-b.item).map((o) => <button className={`agenda-ordinance ${o.id === selected.id ? "active" : ""}`} key={o.id} onClick={() => onSelect(o.id)}><span className="agenda-number">{String(o.item).padStart(2,"0")}</span><span><strong>{o.title}</strong><small>{o.reading}{progress.some((p) => p.ordinanceId === o.id) && <> · <Check size={10}/> Explored</>}</small></span><ChevronRight size={14}/></button>)}</div><button className="agenda-source-link" onClick={() => onOpen(officialDocument("agenda", "Official meeting agenda · January 26, 2026", MEETING.agendaUrl))}><FileText size={15}/> Open the complete agenda <ArrowUpRight size={14}/></button><div className="session-hall-photo"><img src={asset("images/council-chambers.png")} alt="The real Cheyenne City Council Chambers at City Hall, 2101 O’Neil Avenue"/><span><Landmark size={12}/> The real Council Chambers</span></div><div className="session-seat-note"><ShieldCheck size={19}/><strong>Explore, don’t impersonate.</strong><p>Your choices are personal reflections. They do not change the real meeting or cast an official vote.</p></div></aside>
      <div className="ordinance-workspace"><div className="workspace-heading"><div className={`ordinance-icon ${selected.color}`}><OrdinanceIcon ordinance={selected} size={23}/></div><div><span className="eyebrow">AGENDA ITEM {String(selected.item).padStart(2,"0")} · {selected.category.toUpperCase()}</span><h2>{selected.title}</h2></div><span className="pill pill-neutral">{selected.reading}</span></div><div className="workspace-steps">{STAGES.map((s, i) => <button key={s.id} className={`${stage === s.id ? "active" : ""} ${i < stageIndex ? "completed" : ""}`} onClick={() => { setStage(s.id); setSaved(false); }}><span>{i < stageIndex ? <Check size={13}/> : i+1}</span><s.icon size={14}/><strong>{s.label}</strong></button>)}</div>
        <div className="workspace-stage">
          {stage === "read" && <div className="read-stage"><div className="evidence-caption"><span className="status-dot"/> From the official January 26 agenda</div><h3>Start with the actual ordinance.</h3><p className="stage-introduction">{selected.description} Here is the agenda language, without a fictional storyline.</p><blockquote className="ordinance-text"><span className="eyebrow">ORDINANCE · {selected.reading.toUpperCase()}</span><p>{selected.fullTitle}</p><footer>{selected.committee}</footer></blockquote><div className="record-facts"><div><MapPin size={16}/><span>Geographic scope<strong>{selected.area}</strong></span></div><div><Landmark size={16}/><span>Legislative stage<strong>{selected.outcomeLabel}</strong></span></div></div><button className="button button-outline" onClick={() => onOpen(officialDocument(selected.id, `${selected.title} · supporting document`, selected.sourceUrl))}><FileText size={16}/> Read the supporting document <ArrowUpRight size={15}/></button><div className="stage-source-note"><ShieldCheck size={16}/><p>An agenda is a proposal record, not proof of enactment. Follow the session and check the minutes for the recorded action.</p></div></div>}
          {stage === "watch" && <div className="watch-stage"><div className="evidence-caption"><span className="status-dot"/> Official City of Cheyenne meeting video</div><h3>Hear the discussion in the room.</h3><p className="stage-introduction">Watch the archived meeting{selected.timestamp ? " from this ordinance’s agenda segment" : " and follow the agenda"}. Public testimony is a speaker’s perspective, not a verified impact finding.</p><div className="meeting-video"><iframe src={`https://www.youtube-nocookie.com/embed/${MEETING.youtubeId}?start=${selected.timestamp}`} title={`Official Cheyenne City Council meeting: ${selected.title}`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><div className="watch-source-actions"><button className="button button-outline" onClick={() => onOpen(transcriptDocument)}><FileText size={16}/> Read timestamped transcript</button><a className="button button-outline" href={`${MEETING.videoUrl}`} target="_blank" rel="noreferrer"><Video size={16}/> Official video <ArrowUpRight size={14}/></a></div><div className="stage-source-note"><AlertCircle size={16}/><p>Captions are automatically generated and may misidentify people. The official video and minutes are the primary records.</p></div></div>}
          {stage === "impact" && <div className="impact-stage"><div className="stage-heading-row"><div><div className="evidence-caption"><span className="status-dot"/> An evidence-led look beyond the chamber</div><h3>Follow the change into Cheyenne.</h3></div><div className="scenario-control"><button className={!proposed ? "active" : ""} onClick={() => setProposed(false)}>Before</button><button className={proposed ? "active" : ""} onClick={() => setProposed(true)}>If enacted</button></div></div><ImpactSummary ordinance={selected} proposed={proposed}/><ImpactMap selected={selected} onSelect={onSelect} proposed={proposed}/><div className="map-scope-note"><MapPin size={14}/> General locations only · not legal parcel or city boundaries<button onClick={() => onMap(selected.id)}>Open full impact map <ArrowUpRight size={13}/></button></div><div className="knowledge-check"><div className="knowledge-check-title"><Lightbulb size={18}/><span>RECORD CHECK</span></div><h4>{checkpoint.question}</h4><div className="knowledge-answers">{checkpoint.answers.map((choice, i) => <button key={choice} className={answer === i ? i === checkpoint.correct ? "correct" : "incorrect" : ""} onClick={() => setAnswer(i)}><span>{answer === i && i === checkpoint.correct ? <Check size={13}/> : String.fromCharCode(65+i)}</span>{choice}</button>)}</div>{answer !== null && <p className={answer === checkpoint.correct ? "answer-correct" : "answer-incorrect"}>{answer === checkpoint.correct ? "That’s right. The answer follows the original agenda and meeting record." : "Not quite. Revisit the ordinance language above and try again."}</p>}</div></div>}
          {stage === "reflect" && <div className="reflect-stage"><div className="evidence-caption"><MessageSquareText size={14}/> Your personal civic notebook</div><h3>What’s your perspective?</h3><p className="stage-introduction">You’ve seen the record. Save where you stand and the questions you’d bring to the real conversation.</p><div className="position-choices">{[{ id:"support", label:"I support this", icon: CheckCircle2 },{id:"questions",label:"I have questions",icon: MessageSquareText},{id:"oppose",label:"I’m concerned",icon: AlertCircle}].map((p) => <button key={p.id} className={position === p.id ? "selected" : ""} onClick={() => { setPosition(p.id); setSaved(false); }}><p.icon size={20}/>{p.label}</button>)}</div><label className="reflection-label" htmlFor="reflection">Your notes, questions, or reasoning<span>Optional · {reflection.length.toLocaleString()} / 5,000</span></label><textarea id="reflection" className="reflection-input" rows={7} value={reflection} maxLength={5000} onChange={(e) => { setReflection(e.target.value); setSaved(false); }} placeholder="What does this mean for your neighborhood? Which details would you want the council to clarify?"/><div className="suggested-questions"><strong>Questions worth exploring</strong>{selected.questions.map((q) => <button key={q} onClick={() => { setReflection((r) => `${r}${r ? "\n" : ""}${q}`.slice(0,5000)); setSaved(false); }}><PlusQuestion/> {q}</button>)}</div><button className="button button-primary" disabled={saving || (!position && !reflection.trim())} onClick={() => void save("reflect")}>{saving ? <LoaderCircle className="spin" size={16}/> : saved ? <Check size={16}/> : <BookOpen size={16}/>} {saved ? "Saved to your notebook" : "Save my perspective"}</button><div className="stage-source-note"><ShieldCheck size={16}/><p>Saved to your anonymous visitor notebook. This is not an official vote or public comment and is not submitted to the city.</p></div></div>}
        </div>
        {stage !== "reflect" && <div className="workspace-footer"><span><ShieldCheck size={15}/> Real records. Your own understanding.</span><button className="button button-primary" disabled={saving} onClick={() => void save(STAGES[Math.min(stageIndex+1,3)].id)}>{saving ? <LoaderCircle size={16} className="spin"/> : <Check size={16}/>} {stage === "read" ? "Read & continue" : stage === "watch" ? "Continue to impacts" : "Add my perspective"}<ArrowRight size={15}/></button></div>}
      </div>
    </div>
  </section>;
}
function PlusQuestion() { return <ChevronRight size={13}/>; }
